using Numbers2WordsLogic;
using NUnit.Framework;

namespace Numbers2WordsTests
{
    public class Tests
    {
        [Test]
        public void TestsFrom0To99()
        {
            AssertTranslateTest("0", "zero dollars");
            AssertTranslateTest("1", "one dollar");
            AssertTranslateTest("2", "two dollars");
            AssertTranslateTest("3", "three dollars");
            AssertTranslateTest("4", "four dollars");
            AssertTranslateTest("5", "five dollars");
            AssertTranslateTest("6", "six dollars");
            AssertTranslateTest("7", "seven dollars");
            AssertTranslateTest("8", "eight dollars");
            AssertTranslateTest("9", "nine dollars");
            AssertTranslateTest("10", "ten dollars");
            AssertTranslateTest("11", "eleven dollars");
            AssertTranslateTest("12", "twelve dollars");
            AssertTranslateTest("13", "thirteen dollars");
            AssertTranslateTest("14", "fourteen dollars");
            AssertTranslateTest("15", "fifteen dollars");
            AssertTranslateTest("16", "sixteen dollars");
            AssertTranslateTest("17", "seventeen dollars");
            AssertTranslateTest("18", "eighteen dollars");
            AssertTranslateTest("19", "nineteen dollars");
            AssertTranslateTest("20", "twenty dollars");
            AssertTranslateTest("21", "twenty one dollars");
            AssertTranslateTest("22", "twenty two dollars");
            AssertTranslateTest("23", "twenty three dollars");
            AssertTranslateTest("24", "twenty four dollars");
            AssertTranslateTest("25", "twenty five dollars");
            AssertTranslateTest("26", "twenty six dollars");
            AssertTranslateTest("27", "twenty seven dollars");
            AssertTranslateTest("28", "twenty eight dollars");
            AssertTranslateTest("29", "twenty nine dollars");
            AssertTranslateTest("30", "thirty dollars");
            AssertTranslateTest("31", "thirty one dollars");
            AssertTranslateTest("32", "thirty two dollars");
            AssertTranslateTest("33", "thirty three dollars");
            AssertTranslateTest("34", "thirty four dollars");
            AssertTranslateTest("35", "thirty five dollars");
            AssertTranslateTest("36", "thirty six dollars");
            AssertTranslateTest("37", "thirty seven dollars");
            AssertTranslateTest("38", "thirty eight dollars");
            AssertTranslateTest("39", "thirty nine dollars");
            AssertTranslateTest("40", "forty dollars");
            AssertTranslateTest("41", "forty one dollars");
            AssertTranslateTest("42", "forty two dollars");
            AssertTranslateTest("43", "forty three dollars");
            AssertTranslateTest("44", "forty four dollars");
            AssertTranslateTest("45", "forty five dollars");
            AssertTranslateTest("46", "forty six dollars");
            AssertTranslateTest("47", "forty seven dollars");
            AssertTranslateTest("48", "forty eight dollars");
            AssertTranslateTest("49", "forty nine dollars");
            AssertTranslateTest("50", "fifty dollars");
            AssertTranslateTest("51", "fifty one dollars");
            AssertTranslateTest("52", "fifty two dollars");
            AssertTranslateTest("53", "fifty three dollars");
            AssertTranslateTest("54", "fifty four dollars");
            AssertTranslateTest("55", "fifty five dollars");
            AssertTranslateTest("56", "fifty six dollars");
            AssertTranslateTest("57", "fifty seven dollars");
            AssertTranslateTest("58", "fifty eight dollars");
            AssertTranslateTest("59", "fifty nine dollars");
            AssertTranslateTest("60", "sixty dollars");
            AssertTranslateTest("61", "sixty one dollars");
            AssertTranslateTest("62", "sixty two dollars");
            AssertTranslateTest("63", "sixty three dollars");
            AssertTranslateTest("64", "sixty four dollars");
            AssertTranslateTest("65", "sixty five dollars");
            AssertTranslateTest("66", "sixty six dollars");
            AssertTranslateTest("67", "sixty seven dollars");
            AssertTranslateTest("68", "sixty eight dollars");
            AssertTranslateTest("69", "sixty nine dollars");
            AssertTranslateTest("70", "seventy dollars");
            AssertTranslateTest("71", "seventy one dollars");
            AssertTranslateTest("72", "seventy two dollars");
            AssertTranslateTest("73", "seventy three dollars");
            AssertTranslateTest("74", "seventy four dollars");
            AssertTranslateTest("75", "seventy five dollars");
            AssertTranslateTest("76", "seventy six dollars");
            AssertTranslateTest("77", "seventy seven dollars");
            AssertTranslateTest("78", "seventy eight dollars");
            AssertTranslateTest("79", "seventy nine dollars");
            AssertTranslateTest("80", "eighty dollars");
            AssertTranslateTest("81", "eighty one dollars");
            AssertTranslateTest("82", "eighty two dollars");
            AssertTranslateTest("83", "eighty three dollars");
            AssertTranslateTest("84", "eighty four dollars");
            AssertTranslateTest("85", "eighty five dollars");
            AssertTranslateTest("86", "eighty six dollars");
            AssertTranslateTest("87", "eighty seven dollars");
            AssertTranslateTest("88", "eighty eight dollars");
            AssertTranslateTest("89", "eighty nine dollars");
            AssertTranslateTest("90", "ninety dollars");
            AssertTranslateTest("91", "ninety one dollars");
            AssertTranslateTest("92", "ninety two dollars");
            AssertTranslateTest("93", "ninety three dollars");
            AssertTranslateTest("94", "ninety four dollars");
            AssertTranslateTest("95", "ninety five dollars");
            AssertTranslateTest("96", "ninety six dollars");
            AssertTranslateTest("97", "ninety seven dollars");
            AssertTranslateTest("98", "ninety eight dollars");
            AssertTranslateTest("99", "ninety nine dollars");
        }

        [Test]
        public void TestsFrom100To199()
        {
            AssertTranslateTest("100", "one hundred dollars");
            AssertTranslateTest("101", "one hundred and one dollars");
            AssertTranslateTest("102", "one hundred and two dollars");
            AssertTranslateTest("103", "one hundred and three dollars");
            AssertTranslateTest("104", "one hundred and four dollars");
            AssertTranslateTest("105", "one hundred and five dollars");
            AssertTranslateTest("106", "one hundred and six dollars");
            AssertTranslateTest("107", "one hundred and seven dollars");
            AssertTranslateTest("108", "one hundred and eight dollars");
            AssertTranslateTest("109", "one hundred and nine dollars");
            AssertTranslateTest("110", "one hundred and ten dollars");
            AssertTranslateTest("111", "one hundred and eleven dollars");
            AssertTranslateTest("112", "one hundred and twelve dollars");
            AssertTranslateTest("113", "one hundred and thirteen dollars");
            AssertTranslateTest("114", "one hundred and fourteen dollars");
            AssertTranslateTest("115", "one hundred and fifteen dollars");
            AssertTranslateTest("116", "one hundred and sixteen dollars");
            AssertTranslateTest("117", "one hundred and seventeen dollars");
            AssertTranslateTest("118", "one hundred and eighteen dollars");
            AssertTranslateTest("119", "one hundred and nineteen dollars");
            AssertTranslateTest("120", "one hundred and twenty dollars");
            AssertTranslateTest("121", "one hundred and twenty one dollars");
            AssertTranslateTest("122", "one hundred and twenty two dollars");
            AssertTranslateTest("123", "one hundred and twenty three dollars");
            AssertTranslateTest("124", "one hundred and twenty four dollars");
            AssertTranslateTest("125", "one hundred and twenty five dollars");
            AssertTranslateTest("126", "one hundred and twenty six dollars");
            AssertTranslateTest("127", "one hundred and twenty seven dollars");
            AssertTranslateTest("128", "one hundred and twenty eight dollars");
            AssertTranslateTest("129", "one hundred and twenty nine dollars");
            AssertTranslateTest("130", "one hundred and thirty dollars");
            AssertTranslateTest("131", "one hundred and thirty one dollars");
            AssertTranslateTest("132", "one hundred and thirty two dollars");
            AssertTranslateTest("133", "one hundred and thirty three dollars");
            AssertTranslateTest("134", "one hundred and thirty four dollars");
            AssertTranslateTest("135", "one hundred and thirty five dollars");
            AssertTranslateTest("136", "one hundred and thirty six dollars");
            AssertTranslateTest("137", "one hundred and thirty seven dollars");
            AssertTranslateTest("138", "one hundred and thirty eight dollars");
            AssertTranslateTest("139", "one hundred and thirty nine dollars");
            AssertTranslateTest("140", "one hundred and forty dollars");
            AssertTranslateTest("141", "one hundred and forty one dollars");
            AssertTranslateTest("142", "one hundred and forty two dollars");
            AssertTranslateTest("143", "one hundred and forty three dollars");
            AssertTranslateTest("144", "one hundred and forty four dollars");
            AssertTranslateTest("145", "one hundred and forty five dollars");
            AssertTranslateTest("146", "one hundred and forty six dollars");
            AssertTranslateTest("147", "one hundred and forty seven dollars");
            AssertTranslateTest("148", "one hundred and forty eight dollars");
            AssertTranslateTest("149", "one hundred and forty nine dollars");
            AssertTranslateTest("150", "one hundred and fifty dollars");
            AssertTranslateTest("151", "one hundred and fifty one dollars");
            AssertTranslateTest("152", "one hundred and fifty two dollars");
            AssertTranslateTest("153", "one hundred and fifty three dollars");
            AssertTranslateTest("154", "one hundred and fifty four dollars");
            AssertTranslateTest("155", "one hundred and fifty five dollars");
            AssertTranslateTest("156", "one hundred and fifty six dollars");
            AssertTranslateTest("157", "one hundred and fifty seven dollars");
            AssertTranslateTest("158", "one hundred and fifty eight dollars");
            AssertTranslateTest("159", "one hundred and fifty nine dollars");
            AssertTranslateTest("160", "one hundred and sixty dollars");
            AssertTranslateTest("161", "one hundred and sixty one dollars");
            AssertTranslateTest("162", "one hundred and sixty two dollars");
            AssertTranslateTest("163", "one hundred and sixty three dollars");
            AssertTranslateTest("164", "one hundred and sixty four dollars");
            AssertTranslateTest("165", "one hundred and sixty five dollars");
            AssertTranslateTest("166", "one hundred and sixty six dollars");
            AssertTranslateTest("167", "one hundred and sixty seven dollars");
            AssertTranslateTest("168", "one hundred and sixty eight dollars");
            AssertTranslateTest("169", "one hundred and sixty nine dollars");
            AssertTranslateTest("170", "one hundred and seventy dollars");
            AssertTranslateTest("171", "one hundred and seventy one dollars");
            AssertTranslateTest("172", "one hundred and seventy two dollars");
            AssertTranslateTest("173", "one hundred and seventy three dollars");
            AssertTranslateTest("174", "one hundred and seventy four dollars");
            AssertTranslateTest("175", "one hundred and seventy five dollars");
            AssertTranslateTest("176", "one hundred and seventy six dollars");
            AssertTranslateTest("177", "one hundred and seventy seven dollars");
            AssertTranslateTest("178", "one hundred and seventy eight dollars");
            AssertTranslateTest("179", "one hundred and seventy nine dollars");
            AssertTranslateTest("180", "one hundred and eighty dollars");
            AssertTranslateTest("181", "one hundred and eighty one dollars");
            AssertTranslateTest("182", "one hundred and eighty two dollars");
            AssertTranslateTest("183", "one hundred and eighty three dollars");
            AssertTranslateTest("184", "one hundred and eighty four dollars");
            AssertTranslateTest("185", "one hundred and eighty five dollars");
            AssertTranslateTest("186", "one hundred and eighty six dollars");
            AssertTranslateTest("187", "one hundred and eighty seven dollars");
            AssertTranslateTest("188", "one hundred and eighty eight dollars");
            AssertTranslateTest("189", "one hundred and eighty nine dollars");
            AssertTranslateTest("190", "one hundred and ninety dollars");
            AssertTranslateTest("191", "one hundred and ninety one dollars");
            AssertTranslateTest("192", "one hundred and ninety two dollars");
            AssertTranslateTest("193", "one hundred and ninety three dollars");
            AssertTranslateTest("194", "one hundred and ninety four dollars");
            AssertTranslateTest("195", "one hundred and ninety five dollars");
            AssertTranslateTest("196", "one hundred and ninety six dollars");
            AssertTranslateTest("197", "one hundred and ninety seven dollars");
            AssertTranslateTest("198", "one hundred and ninety eight dollars");
            AssertTranslateTest("199", "one hundred and ninety nine dollars");
        }

        [Test]
        public void TestsWithMinus()
        {
            AssertTranslateTest("-200", "minus two hundred dollars");
            AssertTranslateTest("-201", "minus two hundred and one dollars");
            AssertTranslateTest("-202", "minus two hundred and two dollars");
            AssertTranslateTest("-203", "minus two hundred and three dollars");
            AssertTranslateTest("-204", "minus two hundred and four dollars");
            AssertTranslateTest("-205", "minus two hundred and five dollars");
            AssertTranslateTest("-206", "minus two hundred and six dollars");
            AssertTranslateTest("-207", "minus two hundred and seven dollars");
            AssertTranslateTest("-208", "minus two hundred and eight dollars");
            AssertTranslateTest("-209", "minus two hundred and nine dollars");
            AssertTranslateTest("-210", "minus two hundred and ten dollars");
            AssertTranslateTest("-211", "minus two hundred and eleven dollars");
            AssertTranslateTest("-212", "minus two hundred and twelve dollars");
            AssertTranslateTest("-213", "minus two hundred and thirteen dollars");
            AssertTranslateTest("-214", "minus two hundred and fourteen dollars");
            AssertTranslateTest("-215", "minus two hundred and fifteen dollars");
            AssertTranslateTest("-216", "minus two hundred and sixteen dollars");
            AssertTranslateTest("-217", "minus two hundred and seventeen dollars");
            AssertTranslateTest("-218", "minus two hundred and eighteen dollars");
            AssertTranslateTest("-219", "minus two hundred and nineteen dollars");
            AssertTranslateTest("-220", "minus two hundred and twenty dollars");
            AssertTranslateTest("-221", "minus two hundred and twenty one dollars");
            AssertTranslateTest("-222", "minus two hundred and twenty two dollars");
            AssertTranslateTest("-223", "minus two hundred and twenty three dollars");
            AssertTranslateTest("-224", "minus two hundred and twenty four dollars");
            AssertTranslateTest("-225", "minus two hundred and twenty five dollars");
            AssertTranslateTest("-226", "minus two hundred and twenty six dollars");
            AssertTranslateTest("-227", "minus two hundred and twenty seven dollars");
            AssertTranslateTest("-228", "minus two hundred and twenty eight dollars");
            AssertTranslateTest("-229", "minus two hundred and twenty nine dollars");
            AssertTranslateTest("-230", "minus two hundred and thirty dollars");
            AssertTranslateTest("-231", "minus two hundred and thirty one dollars");
            AssertTranslateTest("-232", "minus two hundred and thirty two dollars");
            AssertTranslateTest("-233", "minus two hundred and thirty three dollars");
            AssertTranslateTest("-234", "minus two hundred and thirty four dollars");
            AssertTranslateTest("-235", "minus two hundred and thirty five dollars");
            AssertTranslateTest("-236", "minus two hundred and thirty six dollars");
            AssertTranslateTest("-237", "minus two hundred and thirty seven dollars");
            AssertTranslateTest("-238", "minus two hundred and thirty eight dollars");
            AssertTranslateTest("-239", "minus two hundred and thirty nine dollars");
            AssertTranslateTest("-240", "minus two hundred and forty dollars");
            AssertTranslateTest("-241", "minus two hundred and forty one dollars");
            AssertTranslateTest("-242", "minus two hundred and forty two dollars");
            AssertTranslateTest("-243", "minus two hundred and forty three dollars");
            AssertTranslateTest("-244", "minus two hundred and forty four dollars");
            AssertTranslateTest("-245", "minus two hundred and forty five dollars");
            AssertTranslateTest("-246", "minus two hundred and forty six dollars");
            AssertTranslateTest("-247", "minus two hundred and forty seven dollars");
            AssertTranslateTest("-248", "minus two hundred and forty eight dollars");
            AssertTranslateTest("-249", "minus two hundred and forty nine dollars");
            AssertTranslateTest("-250", "minus two hundred and fifty dollars");
            AssertTranslateTest("-251", "minus two hundred and fifty one dollars");
            AssertTranslateTest("-252", "minus two hundred and fifty two dollars");
            AssertTranslateTest("-253", "minus two hundred and fifty three dollars");
            AssertTranslateTest("-254", "minus two hundred and fifty four dollars");
            AssertTranslateTest("-255", "minus two hundred and fifty five dollars");
            AssertTranslateTest("-256", "minus two hundred and fifty six dollars");
            AssertTranslateTest("-257", "minus two hundred and fifty seven dollars");
            AssertTranslateTest("-258", "minus two hundred and fifty eight dollars");
            AssertTranslateTest("-259", "minus two hundred and fifty nine dollars");
            AssertTranslateTest("-260", "minus two hundred and sixty dollars");
            AssertTranslateTest("-261", "minus two hundred and sixty one dollars");
            AssertTranslateTest("-262", "minus two hundred and sixty two dollars");
            AssertTranslateTest("-263", "minus two hundred and sixty three dollars");
            AssertTranslateTest("-264", "minus two hundred and sixty four dollars");
            AssertTranslateTest("-265", "minus two hundred and sixty five dollars");
            AssertTranslateTest("-266", "minus two hundred and sixty six dollars");
            AssertTranslateTest("-267", "minus two hundred and sixty seven dollars");
            AssertTranslateTest("-268", "minus two hundred and sixty eight dollars");
            AssertTranslateTest("-269", "minus two hundred and sixty nine dollars");
            AssertTranslateTest("-270", "minus two hundred and seventy dollars");
            AssertTranslateTest("-271", "minus two hundred and seventy one dollars");
            AssertTranslateTest("-272", "minus two hundred and seventy two dollars");
            AssertTranslateTest("-273", "minus two hundred and seventy three dollars");
            AssertTranslateTest("-274", "minus two hundred and seventy four dollars");
            AssertTranslateTest("-275", "minus two hundred and seventy five dollars");
            AssertTranslateTest("-276", "minus two hundred and seventy six dollars");
            AssertTranslateTest("-277", "minus two hundred and seventy seven dollars");
            AssertTranslateTest("-278", "minus two hundred and seventy eight dollars");
            AssertTranslateTest("-279", "minus two hundred and seventy nine dollars");
            AssertTranslateTest("-280", "minus two hundred and eighty dollars");
            AssertTranslateTest("-281", "minus two hundred and eighty one dollars");
            AssertTranslateTest("-282", "minus two hundred and eighty two dollars");
            AssertTranslateTest("-283", "minus two hundred and eighty three dollars");
            AssertTranslateTest("-284", "minus two hundred and eighty four dollars");
            AssertTranslateTest("-285", "minus two hundred and eighty five dollars");
            AssertTranslateTest("-286", "minus two hundred and eighty six dollars");
            AssertTranslateTest("-287", "minus two hundred and eighty seven dollars");
            AssertTranslateTest("-288", "minus two hundred and eighty eight dollars");
            AssertTranslateTest("-289", "minus two hundred and eighty nine dollars");
            AssertTranslateTest("-290", "minus two hundred and ninety dollars");
            AssertTranslateTest("-291", "minus two hundred and ninety one dollars");
            AssertTranslateTest("-292", "minus two hundred and ninety two dollars");
            AssertTranslateTest("-293", "minus two hundred and ninety three dollars");
            AssertTranslateTest("-294", "minus two hundred and ninety four dollars");
            AssertTranslateTest("-295", "minus two hundred and ninety five dollars");
            AssertTranslateTest("-296", "minus two hundred and ninety six dollars");
            AssertTranslateTest("-297", "minus two hundred and ninety seven dollars");
            AssertTranslateTest("-298", "minus two hundred and ninety eight dollars");
            AssertTranslateTest("-299", "minus two hundred and ninety nine dollars");
        }

        [Test]
        public void TestsWithFractionalPart()
        {
            AssertTranslateTest("400.00", "four hundred dollars and zero cents");
            AssertTranslateTest("401.01", "four hundred and one dollars and one cent");
            AssertTranslateTest("402.02", "four hundred and two dollars and two cents");
            AssertTranslateTest("403.03", "four hundred and three dollars and three cents");
            AssertTranslateTest("404.04", "four hundred and four dollars and four cents");
            AssertTranslateTest("405.05", "four hundred and five dollars and five cents");
            AssertTranslateTest("406.06", "four hundred and six dollars and six cents");
            AssertTranslateTest("407.07", "four hundred and seven dollars and seven cents");
            AssertTranslateTest("408.08", "four hundred and eight dollars and eight cents");
            AssertTranslateTest("409.09", "four hundred and nine dollars and nine cents");
            AssertTranslateTest("410.10", "four hundred and ten dollars and ten cents");
            AssertTranslateTest("411.11", "four hundred and eleven dollars and eleven cents");
            AssertTranslateTest("412.12", "four hundred and twelve dollars and twelve cents");
            AssertTranslateTest("413.13", "four hundred and thirteen dollars and thirteen cents");
            AssertTranslateTest("414.14", "four hundred and fourteen dollars and fourteen cents");
            AssertTranslateTest("415.15", "four hundred and fifteen dollars and fifteen cents");
            AssertTranslateTest("416.16", "four hundred and sixteen dollars and sixteen cents");
            AssertTranslateTest("417.17", "four hundred and seventeen dollars and seventeen cents");
            AssertTranslateTest("418.18", "four hundred and eighteen dollars and eighteen cents");
            AssertTranslateTest("419.19", "four hundred and nineteen dollars and nineteen cents");
            AssertTranslateTest("420.20", "four hundred and twenty dollars and twenty cents");
            AssertTranslateTest("421.21", "four hundred and twenty one dollars and twenty one cents");
            AssertTranslateTest("422.22", "four hundred and twenty two dollars and twenty two cents");
            AssertTranslateTest("423.23", "four hundred and twenty three dollars and twenty three cents");
            AssertTranslateTest("424.24", "four hundred and twenty four dollars and twenty four cents");
            AssertTranslateTest("425.25", "four hundred and twenty five dollars and twenty five cents");
            AssertTranslateTest("426.26", "four hundred and twenty six dollars and twenty six cents");
            AssertTranslateTest("427.27", "four hundred and twenty seven dollars and twenty seven cents");
            AssertTranslateTest("428.28", "four hundred and twenty eight dollars and twenty eight cents");
            AssertTranslateTest("429.29", "four hundred and twenty nine dollars and twenty nine cents");
            AssertTranslateTest("430.30", "four hundred and thirty dollars and thirty cents");
            AssertTranslateTest("431.31", "four hundred and thirty one dollars and thirty one cents");
            AssertTranslateTest("432.32", "four hundred and thirty two dollars and thirty two cents");
            AssertTranslateTest("433.33", "four hundred and thirty three dollars and thirty three cents");
            AssertTranslateTest("434.34", "four hundred and thirty four dollars and thirty four cents");
            AssertTranslateTest("435.35", "four hundred and thirty five dollars and thirty five cents");
            AssertTranslateTest("436.36", "four hundred and thirty six dollars and thirty six cents");
            AssertTranslateTest("437.37", "four hundred and thirty seven dollars and thirty seven cents");
            AssertTranslateTest("438.38", "four hundred and thirty eight dollars and thirty eight cents");
            AssertTranslateTest("439.39", "four hundred and thirty nine dollars and thirty nine cents");
            AssertTranslateTest("440.40", "four hundred and forty dollars and forty cents");
            AssertTranslateTest("441.41", "four hundred and forty one dollars and forty one cents");
            AssertTranslateTest("442.42", "four hundred and forty two dollars and forty two cents");
            AssertTranslateTest("443.43", "four hundred and forty three dollars and forty three cents");
            AssertTranslateTest("444.44", "four hundred and forty four dollars and forty four cents");
            AssertTranslateTest("445.45", "four hundred and forty five dollars and forty five cents");
            AssertTranslateTest("446.46", "four hundred and forty six dollars and forty six cents");
            AssertTranslateTest("447.47", "four hundred and forty seven dollars and forty seven cents");
            AssertTranslateTest("448.48", "four hundred and forty eight dollars and forty eight cents");
            AssertTranslateTest("449.49", "four hundred and forty nine dollars and forty nine cents");
            AssertTranslateTest("450.50", "four hundred and fifty dollars and fifty cents");
            AssertTranslateTest("451.51", "four hundred and fifty one dollars and fifty one cents");
            AssertTranslateTest("452.52", "four hundred and fifty two dollars and fifty two cents");
            AssertTranslateTest("453.53", "four hundred and fifty three dollars and fifty three cents");
            AssertTranslateTest("454.54", "four hundred and fifty four dollars and fifty four cents");
            AssertTranslateTest("455.55", "four hundred and fifty five dollars and fifty five cents");
            AssertTranslateTest("456.56", "four hundred and fifty six dollars and fifty six cents");
            AssertTranslateTest("457.57", "four hundred and fifty seven dollars and fifty seven cents");
            AssertTranslateTest("458.58", "four hundred and fifty eight dollars and fifty eight cents");
            AssertTranslateTest("459.59", "four hundred and fifty nine dollars and fifty nine cents");
            AssertTranslateTest("460.60", "four hundred and sixty dollars and sixty cents");
            AssertTranslateTest("461.61", "four hundred and sixty one dollars and sixty one cents");
            AssertTranslateTest("462.62", "four hundred and sixty two dollars and sixty two cents");
            AssertTranslateTest("463.63", "four hundred and sixty three dollars and sixty three cents");
            AssertTranslateTest("464.64", "four hundred and sixty four dollars and sixty four cents");
            AssertTranslateTest("465.65", "four hundred and sixty five dollars and sixty five cents");
            AssertTranslateTest("466.66", "four hundred and sixty six dollars and sixty six cents");
            AssertTranslateTest("467.67", "four hundred and sixty seven dollars and sixty seven cents");
            AssertTranslateTest("468.68", "four hundred and sixty eight dollars and sixty eight cents");
            AssertTranslateTest("469.69", "four hundred and sixty nine dollars and sixty nine cents");
            AssertTranslateTest("470.70", "four hundred and seventy dollars and seventy cents");
            AssertTranslateTest("471.71", "four hundred and seventy one dollars and seventy one cents");
            AssertTranslateTest("472.72", "four hundred and seventy two dollars and seventy two cents");
            AssertTranslateTest("473.73", "four hundred and seventy three dollars and seventy three cents");
            AssertTranslateTest("474.74", "four hundred and seventy four dollars and seventy four cents");
            AssertTranslateTest("475.75", "four hundred and seventy five dollars and seventy five cents");
            AssertTranslateTest("476.76", "four hundred and seventy six dollars and seventy six cents");
            AssertTranslateTest("477.77", "four hundred and seventy seven dollars and seventy seven cents");
            AssertTranslateTest("478.78", "four hundred and seventy eight dollars and seventy eight cents");
            AssertTranslateTest("479.79", "four hundred and seventy nine dollars and seventy nine cents");
            AssertTranslateTest("480.80", "four hundred and eighty dollars and eighty cents");
            AssertTranslateTest("481.81", "four hundred and eighty one dollars and eighty one cents");
            AssertTranslateTest("482.82", "four hundred and eighty two dollars and eighty two cents");
            AssertTranslateTest("483.83", "four hundred and eighty three dollars and eighty three cents");
            AssertTranslateTest("484.84", "four hundred and eighty four dollars and eighty four cents");
            AssertTranslateTest("485.85", "four hundred and eighty five dollars and eighty five cents");
            AssertTranslateTest("486.86", "four hundred and eighty six dollars and eighty six cents");
            AssertTranslateTest("487.87", "four hundred and eighty seven dollars and eighty seven cents");
            AssertTranslateTest("488.88", "four hundred and eighty eight dollars and eighty eight cents");
            AssertTranslateTest("489.89", "four hundred and eighty nine dollars and eighty nine cents");
            AssertTranslateTest("490.90", "four hundred and ninety dollars and ninety cents");
            AssertTranslateTest("491.91", "four hundred and ninety one dollars and ninety one cents");
            AssertTranslateTest("492.92", "four hundred and ninety two dollars and ninety two cents");
            AssertTranslateTest("493.93", "four hundred and ninety three dollars and ninety three cents");
            AssertTranslateTest("494.94", "four hundred and ninety four dollars and ninety four cents");
            AssertTranslateTest("495.95", "four hundred and ninety five dollars and ninety five cents");
            AssertTranslateTest("496.96", "four hundred and ninety six dollars and ninety six cents");
            AssertTranslateTest("497.97", "four hundred and ninety seven dollars and ninety seven cents");
            AssertTranslateTest("498.98", "four hundred and ninety eight dollars and ninety eight cents");
            AssertTranslateTest("499.99", "four hundred and ninety nine dollars and ninety nine cents");
        }

        [Test]
        public void TestsLargeNumbers()
        {
            AssertTranslateTest("100", "one hundred dollars");
            AssertTranslateTest("1000", "one thousand dollars");
            AssertTranslateTest("1234", "one thousand and two hundred thirty four dollars");
            AssertTranslateTest("10000", "ten thousand dollars");
            AssertTranslateTest("12345", "twelve thousand and three hundred forty five dollars");
            AssertTranslateTest("100000", "one hundred thousand dollars");
            AssertTranslateTest("123456", "one hundred and twenty three thousand four hundred fifty six dollars");
            AssertTranslateTest("1000000", "one million dollars");
            AssertTranslateTest("1234567", "one million and two hundred thirty four thousand five hundred sixty seven dollars");
            AssertTranslateTest("10000000", "ten million dollars");
            AssertTranslateTest("12345678", "twelve million three hundred and forty five thousand six hundred seventy eight dollars");
            AssertTranslateTest("100000000", "one hundred million dollars");
            AssertTranslateTest("1000000000", "one billion dollars");
        }

        private void AssertTranslateTest(string number, string expectedResult)
        {
            var result = Translator.Translate(number);
            Assert.AreEqual(expectedResult, result);
        }
    }
}